### PR TITLE
Pi web console

### PR DESCRIPTION
**Pull request by tekkies**
This is the web console.  It sits in it's own folder and the readme is self-explanatory, including screenshot.

I've recently freshly installed it on windows and a raspberry pi and found it useful.

### CODE REVIEW

**Comment by DamonHD** [comment]
Andy, wow, thank you!

I'm not going to have time today to give this the attention it deserves but maybe here are some things we should discuss off-line to get this integrated.

  1) License statement in each file.
  2) Effects on files outside your source tree.
  3) Is this the best repo for this code?  I honestly don't know yet, but maybe it should be showcased in a separate repo.  Let's discuss.

Thanks again

Damon

**Comment by tekkies** [comment]
Sounds good. Andy

**Comment by Denzo77** [comment]
Looks interesting!

I'm in favour of this getting it's own repo. It feels like it could easily grow beyond the scope of this one.

If you're happy with licensing it as Apache 2.0, our standard licensing headers are here: https://github.com/opentrv/OpenTRV-docs/blob/master/docs/licence-notes.txt

**Comment by Denzo77** [comment]
Closed as belongs in own repo

**Pull request closed without merging**
